Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
ECSCluster:
  Type: 'AWS::ECS::Cluster'
  Properties:
    ClusterName: MyFargateCluster
    CapacityProviders:
      - FARGATE
      - FARGATE_SPOT
  taskdefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities:
        - "EC2"
        - "FARGATE"
      ContainerDefinitions:
         Name: "Nodejs"
         Image: "467509542122.dkr.ecr.us-east-1.amazonaws.com/my2ndrepo:latest"
         Cpu: 256
         Memory: 512
         Essential: true

    
